### ISSUE TITLE
running builtin-success-g-set-lastindex-err.js crashes chrome browser 

### ISSUE THREAD

**Issue by dissu** [bakkot/test262-web-runner#4]
Running test262 with the 'test262-web-runner' makes my chrome browser crash.

This issue of test262 seems related to the problem.
https://github.com/tc39/test262/issues/756

This is my test environment
  Ubuntu 16.04
  Chrome version 54.0.2840.59 (64-bit)

And this is the test case makes the browser crash.
[+] RegExp
  [+] prototype
    [+] Symbol.match
      builtin-success-g-set-lastindex-err.js

Have you experienced a similar problem?

**Comment by bakkot** [comment]
Sorry for the delay in getting back to you.

It seems to work for me currently. Both test262 and Chrome have been updated in the meantime, so I'm guessing this was fixed. If it still happens for you, please comment and/or reopen this and let me know your version of Chrome and I'll try to figure out where the issue is coming from.
